server:
  disable: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://service-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: job_traefik-access-log
    static_configs:
      - targets:
          - localhost
        labels:
          job: label-job-traefik-access-log
          __path__: /log/access.log
