server:
  disable: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: traefik-access-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: traefik
          __path__: /logs/access.log
