####################################### Services
services:
  service-promtail:
    image: ahmettoguz/promtail:3.4.3
    container_name: container-promtail
    volumes:
      - volume-promtail:/tmp
      - ${LOG_DIRECTORY}:/log
      - ./config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - network-monitor
    restart: ${RESTART_POLICY}

####################################### Networks
networks:
  network-monitor:
    external: true

####################################### Volumes
volumes:
  volume-promtail:
    name: volume-promtail
